version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - run: yarn cache dir
      - run: node node_modules/jest/bin/jest.js

  ios:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: brew install yarn
      - run: yarn
      - run: yarn cache dir
      - run: node node_modules/jest/bin/jest.js

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - ios
